### PR TITLE
Be able to add a static css string to the global CSSStyleSheet

### PR DESCRIPTION
**Pull request by dustin-H**
- Created this functionality for `addCSS`
- Renamed `toCSS` to `addCSS`
- Added a deprecation warning for `toCSS` (However it still works!)
- Updated the docs

### CODE REVIEW

**Comment by robinweser** [comment]
Cool thanks! Seems like a legit use case for third-party modules and legacy code. Could you perhaps tell why you'd want to renamed `toCSS`?

**Comment by dustin-H** [comment]
I renamed it, because it is in my opinion semantic more logical. Hope you understand.

May we should print out a warning to the logs when this function is used with a string like 

> "You should not use global css because you may break other stuff! Please think about transfering your css to look-js-styles."

Just an idea :smiley:

**Comment by robinweser** [comment]
I don't think we need a warning, but point out within the docs that the static version is used at own risk. I will add that soon

**Comment by dustin-H** [comment]
Nice, thanks!

**Pull request merged**
